services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DB_PATH=${DB_PATH}
      - AI_DIFFICULTY=${AI_DIFFICULTY}
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    restart: unless-stopped