services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_PORT:-3443}:3443"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - JWT_SECRET=${JWT_SECRET:-dev_jwt_secret}
      - COOKIE_SECRET=${COOKIE_SECRET:-dev_cookie_secret}
      - DB_PATH=${DB_PATH:-/app/data/database.sqlite}
      - FRONTEND_URL=${FRONTEND_URL:-https://localhost:9000}
      - BACKEND_URL=${BACKEND_URL:-https://localhost:3443}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-9000}:9000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/certs:/app/certs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - BACKEND_URL=${BACKEND_URL:-https://localhost:3443}
    depends_on:
      - backend
    restart: unless-stopped