services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_PORT:-3443}:3443"
    volumes:
      - backend_code:/app
      - backend_node_modules:/app/node_modules
      - app_data:/app/data
      - ssl_certs:/app/certs
    environment:
      - JWT_SECRET=${JWT_SECRET:-dev_jwt_secret}
      - COOKIE_SECRET=${COOKIE_SECRET:-dev_cookie_secret}
      - DB_PATH=${DB_PATH:-/app/data/database.sqlite}
      - FRONTEND_URL=${FRONTEND_URL:-https://localhost:9000}
      - BACKEND_URL=${BACKEND_URL:-https://localhost:3443}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-9000}:9000"
    volumes:
      - frontend_code:/app
      - frontend_node_modules:/app/node_modules
      - ssl_certs:/app/certs
    environment:
      - BACKEND_URL=${BACKEND_URL:-https://localhost:3443}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_code:
  frontend_code:
  backend_node_modules:
  frontend_node_modules:
  app_data:
  ssl_certs: